import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AppVersion } from "@/components/shared/app-version";
import { cn } from "@/lib/utils";
import Aside from "@/components/shared/aside/aside";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={cn(
            "flex w-full min-h-screen",
            "bg-[linear-gradient(222deg,#CE4257_0%,#FF7F51_100%)]",
          )}
        >
          <Aside />

          <main className="flex-1 bg-zinc-100 my-6 rounded-l-2xl">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
